// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgmjhfxqcaefsfqdvkib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnbWpoZnhxY2FlZnNmcWR2a2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODQwMDcsImV4cCI6MjA2NDU2MDAwN30.JXTD6hEXukengZ68bCTsf9JGQ3Gs8CIhxDSrUVAFyJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);